### ISSUE TITLE
Бот не работает

### ISSUE THREAD

**Issue by yuri25** [akzhar/SearchApartmentsBot#1]
Здравствуйте.  Я набрал в телеграме как Вы написали /start  затем /help - в ответ ничего:( 
По имени AdsSubscribeBot этот бот присутствует в телеграм, но ничего не делает. Пытался также отправить ему ссылку с авито - в ответ аналогично тишина. Подскажите что нужно сделать чтобы заработал? Спасибо.

**Comment by akzhar** [comment]
Здравствуйте.
Бот еще в разработке, я периодически запускаю его локально. На сервере пока не запущен.
Добавил информацию об этом в описание (README.md)

Как только мне удастся запустить его на сервере я закрою это issue.

**Comment by akzhar** [comment]
Бот размещен на сервере. 
На данный момент поддерживает сайты Youla, Cian, Domofond, Domclick.
Сайт Avito временно не поддерживается.
